:toc:
:toclevels: 4

= Wayk Den PowerShell Cmdlet

WaykDen-ps is a PowerShell cmdlet for Wayk Den, the centralized server for https://wayk.devolutions.net[Devolutions Wayk Now]. For assistance or feature requests, please use the https://forum.devolutions.net/#WaykNow[Wayk Now forums] or open a ticket on this github project.

Make sure you have all software prerequisites (<<Installation>> section) then read our quick link:docs\getting-started-argo.adoc[getting started guide (Argo tunnel)] or link:docs\getting-started-azure.adoc[getting started guide (Azure VM)]. Once you have been familiarized with Wayk Den, come back to this page for more details on specific aspects of the software.

== Installation

=== PowerShell Core

On Windows, the regular PowerShell already installed can be used. On macOS and Linux, you need PowerShell Core 6.0:

PowerShell Core 6.0::
https://github.com/PowerShell/PowerShell#get-powershell

To launch a PowerShell Core terminal, use the `pwsh` command.

=== Wayk Den PowerShell module

A powershell module is available to configure and manage the Wayk Den server. It is available on PSGallery or it could be built directly from https://github.com/Devolutions/WaykDen-ps[source code]. We recommand to install the latest version available on PSGallery, but if needed, a section describe how to build it if you need it.

==== Installation from PSGallery

The Wayk Den PowerShell module is https://www.powershellgallery.com/packages/WaykDen[available on PSGallery].

[source,sh]
----
Install-Module -Name WaykDen
Import-Module WaykDen
----

If you encounter issues with the `Install-Module` command, you may have to https://docs.microsoft.com/en-ca/powershell/gallery/installing-psget[install or update PowerShellGet].

You can then list all commands exported from the `WaykDen` module:

[source,sh]
----
Get-Command -Module WaykDen
----

When a new version comes out, you can update the cmdlet and restart Wayk Den to upgrade. The updated cmdlet will point to newer versions of the docker containers used in Wayk Den, so upgrading is a simple matter of restarting Wayk Den:

[source,sh]
----
Update-Module -Name WaykDen
Import-Module WaykDen
Restart-WaykDen
----

==== Installation from Source

If you have installed the module from PSGallery, this section is not useful for you. You can jump to the next section. 

To build the Cmdlet, you will need the .NET Core 2.2 SDK and the .NET Framework 4.7.2 SDK. The latter is only needed if you want to support PowerShell for Windows.

 .NET Core 2.2 SDK::
https://dotnet.microsoft.com/download

 .NET Framework 4.7.2 SDK::
https://dotnet.microsoft.com/download/dotnet-framework/net472

From PowerShell, run the build.ps1 script, and then load the resulting PowerShell module:

[source,sh]
----
.\build.ps1
Import-Module "./WaykDen" -Force
----

=== Docker Installation

Wayk Den is composed of multiple microservices running inside Docker containers. The PowerShell cmdlet simplifies the usage of Docker for users not familiar with it. For more advanced users, the cmdlet can export a usable docker-compose configuration file.

==== Windows Server 2019

The official way of running Wayk Den on Windows Server is to use the built-in support for Windows containers instead of installing Docker Desktop for Windows and running Linux containers. If you intend to run Wayk Den inside a virtual machine, using Windows Server and Windows containers is the recommended approach because it does not require Docker Desktop for Windows and a Hyper-V virtual machine.

Install or update NuGet and PowerShellGet:
----
$ Install-PackageProvider -Name NuGet -Force
$ Install-Module -Name PowerShellGet -Force
----

Check if the Windows Server 'Containers' feature is installed, then install it:
----
$ Get-WindowsFeature | Where-Object { $_.Name -Like 'Containers' }
$ Install-WindowsFeature -Name Containers -Restart
----

Install the Microsoft Docker provider:
----
$ Install-Module -Name DockerMsftProvider -Force
$ Install-Package -Name docker -ProviderName DockerMsftProvider -Force
----

Start the docker service if it is not currently running:
----
$ Get-Service | Where-Object { $_.Name -Like 'docker' }
$ Start-Service -Name docker
----

==== Windows 10

On Windows 10, the recommended option is to use https://hub.docker.com/editions/community/docker-ce-desktop-windows[Docker Desktop for Windows]. This version of Docker requires Hyper-V for Linux container support, making it suitable for testing on a physical machine, but not so much for a virtual machine because of limited support of Docker Desktop for Windows in virtualized environments. If you want to try Wayk Den inside a virtual machine, use Windows Server 2019 instead with Windows containers.

For bind mount support with Linux containers on Windows, you need to go in the Docker settings and https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c[select the required drives from the "Shared Drives" section].

==== macOS

On macOS, follow the official https://docs.docker.com/docker-for-mac/[Docker Desktop getting started guide].

==== Linux

On Linux, follow one of the https://docs.docker.com/install/linux/docker-ce/ubuntu/[distribution-specific getting started guides], then do not forget to https://docs.docker.com/install/linux/linux-postinstall/[add your user to the docker group] after installation.

To confirm that Docker is up and running, use the `docker run hello-world` command. If you don't see the "Hello from Docker!" message, something is wrong with your Docker installation.

== Configuration

All Wayk Den commands accept a -ConfigPath parameter to point to a directory where various configuration files are kept. If this parameter is not specified, the current working directory is used by default.

The first step is to create a Wayk Den configuration file with mandatory parameters using the `New-WaykDenConfig` command.

You need to choose a realm for your Wayk Den, such as "contoso.net". This realm does not need to be a valid DNS domain name, but it will become your Wayk Den realm used in various places, including the peer-to-peer certificates generated by the Wayk Den built-in certificate authority.

The second mandatory parameter is the external URL at which the Wayk Den will be exposed. We recommend using the "den" subdomain under the domain of your choice, such as "den.contoso.net". The protocol prefix (`http://` or `https://`) also needs to be included.

Create a new Wayk Den configuration file, using "contoso.net" as realm and "https://den.contoso.net" as the external url:

[source, sh]
----
PS > New-WaykDenConfig -Realm contoso.net -ExternalUrl https://den.contoso.net -ListenerUrl http://localhost:4000
----

The listener url is used to specify the listening protocol and port on the machine where Wayk Den is running. To listen in https, a certificate needs to be imported before changing the listener URL protocol.

=== Certificate configuration

==== Using certificates with Wayk Den

To expose Wayk Den to the external world, you will need a TLS certificate from a trusted certificate authority such as https://letsencrypt.org/[Let's Encrypt]. Wayk Now will validate certificates in the same way as a browser does for a website.

If you wish to make your own certificate authority, the Root CA certificate will need to be installed in each machine's certificate trust store. If the system browser can validate it, Wayk Now should be able to validate it as well, it's just a lot more work.

Before going any further, check the following points:

1. The certificate name matches your configured external URL. This means that if your external URL is "https://den.contoso.com" then your certificate name should be "den.contoso.com" or "*.contoso.com" if you have a wildcard certificate.

2. The certificate is either in pem + key or pfx (PKCS#12) format. The private key password is only supported for the pfx format.

3. The certificate file contains the certificate *chain* excluding the Root CA. This means that in most cases, you should have a leaf certificate, followed by one or more intermediate certificates. If validation works in a browser but not in Wayk Now, the intermediate certificate is likely missing.

[[certificate-command]]The PEM format is the simplest to work with, since it is the Base64 representation of the DER-encoded certificate in between "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----" tags. To add the intermediate certificate to the certificate file, just append it after your leaf certificate in a text editor.

[source, sh]
----
PS > Import-WaykDenCertificate -CertificateFile /path/to/certificate.pem -PrivateKeyFile /path/to/private_key.key
----

[source, sh]
----
PS > Import-WaykDenCertificate -CertificateFile /path/to/certificate.pfx -Password <password>
----

If you want to roll your own certificate authority, you can check link:docs\smallstep-ca.adoc[smallstep ca].

=== Relay Configuration

To get started, it is recommended to try using our existing relay servers, even if you intend to deploy your own servers later on. It is the quickest path to getting something functional up and running.

Set your Jet Relay Url to `https://api.jet-relay.net`:

[source, sh]
----
PS > Set-WaykDenConfig -JetRelayUrl https://api.jet-relay.net
----

Continue your initial configuration, and once you know it is working, come back to the link:docs\devolutions-jet.adoc[Devolutions Jet] page for more information on how to deploy your own relays.

== Data Persistence

Aside from the Wayk Den configuration files, all Wayk Den data is stored inside a https://www.mongodb.com[MongoDB database]. If you do not specify a database, a simple MongoDB container will be launched with a docker volume attached to it. While this is fine for a lot of use cases, using a single MongoDB container instance is not suitable for high availability scenarios.

To point Wayk Den to an existing MongoDB server, you need to configure a database connection string, and set MongoDB as external to avoid launching a MongoDB container instance:

----
PS > Set-WaykDenConfig -MongoExternal $true -MongoUrl 'mongodb://mongo-server:27017'
----

=== Database Backup

MongoDB database backups can be done using the https://docs.mongodb.com/manual/reference/program/mongodump/[`mongodump` command-line tool]. For simplicity, the `Backup-WaykDenData` command can be used to streamline the process:

----
PS > Backup-WaykDenData -BackupPath .\den-backup.tgz -Verbose
----

The `Backup-WaykDenData` is only usable with a non-external MongoDB database. You can add the `-Verbose` parameter to show the docker commands used to call `mongodump` inside a container for reference.

=== Database Restore

A MongoDB database can be restored from a backup using the https://docs.mongodb.com/manual/reference/program/mongorestore/[`mongorestore` command-line tool]. For obvious reasons, you should be careful about restoring a database, as the operation will overwrite the current data and replace it with the one from the backup.

Just like `Backup-WaykDenData`, `Restore-WaykDenData` should only be used with a non-external MongoDB database. A proper restore involves stopping Wayk Den, restoring data from the backup file, then restarting Wayk Den. Since Stop-WaykDen stops the database container, `Restore-WaykDenData` will automatically start it for the restore operation.

----
PS > Stop-WaykDen
PS > Restore-WaykDenData -BackupPath .\den-backup.tgz -Verbose
PS > Restart-WaykDen
----

== Running

Start Wayk Den, and wait for all microservices to start:

[source, sh]
----
PS > Start-WaykDen
----

Once started, Wayk Den listens on http://localhost:4000 by default. We recommend using a reverse tunnel such as https://ngrok.com/[ngrok] or https://www.cloudflare.com/en-ca/products/argo-tunnel/[argo tunnels] from Cloudflare. In this case, a tunnel is used to expose localhost:4000 on the den.contoso.net external url.

You can check that all containers are up and running with the `docker ps -f network=den-network` command.

To confirm everything is correctly configured, you should be able to get a response from the Wayk Den well known configuration endpoint:

[source, sh]
----
curl http://localhost:4000/.well-known/configuration
{"den_router_uri":"https://den.contoso.net/cow","lucid_uri":"https://den.contoso.net/lucid","realm":"contoso.net","wayk_client_id":"zqdvSbCRWdDrj1fQXwzPQbCg"}
----

If you have correctly configured external access, you should be able to get the same response using the external configuration URL (https://den.contoso.net/.well-known/configuration).

Stop Wayk Den, and wait for all microservices to stop:

[source, sh]
----
PS > Stop-WaykDen
----

=== User Management

User using Wayk Now client can log in to be authenticated with Wayk Den Server. The server, by default, will provide a Wayk Den ID to any user who wants to connect to it.

To authenticate user, Wayk Den can be configured to use a specific user group through LDAP integration. Two options are supported: Active Directory and JumpCloud. 

In order to fetch user and group information, a user with read-only LDAP access must first be created.

==== Active Directory

To integrate Active Directory, here is a list of the required parameters:

* LdapServerUrl: ldap://_ldap-server_
* LdapUsername, LdapPassword
* LdapUserGroup (optional)

It is important to specify the server IP since there is not DNS resolution in the docker container. The user used should be a user with only read-only access. A section below explains how to create a such user. Finally, the user group is not mandatory. If it is not specified, all users will be accepted. If it is specified, only users from that group will be able to be authenticated.

The following command will set LDAP property value for active directory. 

[source, sh]
----
Set-WaykDenConfig -LdapServerType ActiveDirectory -LdapUsername ldap-user@contoso.local -LdapPassword ldap-password -LdapServerUrl ldap://ldap-server -LdapUserGroup 'Domain Users'
---- 

===== User creation with read-only access

By default, a new user created in active directory has read-only access on the LDAP server. But that user is also member of the group Domain Users by default. Being member of that group is enough to be able to use that user and log on any domain's computer. To avoid that, we suggest to use a user who is not a member of Domain Users group and has only read-only access on the LDAP server. To do that, a few steps is needed.

First, a new group has to be created, let's say "Read-only Users". Then a new user can be created and added only to that group. After that, the new group can be set as primary group for the user. And finally, the user can be removed from the Domain Users group. This user should be used to configured WaykDen Server.

==== JumpCloud

https://jumpcloud.com/[JumpCloud] is a cloud service who help you to centralize user management. You can create users and groups then use the service call "LDAP-as-a-Service" to access those users and groups from WaykDen. You can read more on https://support.jumpcloud.com/customer/en/portal/articles/2439911-using-jumpcloud-s-ldap-as-a-service[how to use JumpCloud's LDAP-as-a-Service]. 

To integrate Jump Cloud with Wayk Den, here is a list of the required parameters:

* LdapServerUrl (ldaps://ldap.jumpcloud.com:636)
* LdapUsername, LdapPassword
* LdapBaseDn: Distinguished Name to retrieve users and groups
* LdapUserGroup (optional)

The LDAP server url should be set to ldaps://ldap.jumpcloud.com:636. JumpCloud provide a non secure access as well, but we don't recommand it. A user who can read the ldap directory should be created following steps https://support.jumpcloud.com/customer/en/portal/articles/2439911-using-jumpcloud-s-ldap-as-a-service#createuser[here]. The username has to be provided with the Distinguished Name (DN), something like `uid=_LDAP_BINDING_USER_,ou=Users,o=_YOUR_ORG_ID_,dc=jumpcloud,dc=com`. The base DN is similar and should be set to `ou=Users,o=_YOUR_ORG_ID_,dc=jumpcloud,dc=com`. Finally, a user group name can be specified to limit user to that group.

The following command will set LDAP property value for JumpCloud.

[source, sh]
----
Set-WaykDenConfig -LdapServerType JumpCloud -LdapUsername "uid=ldap-user,ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com" -LdapPassword ldap-password -LdapServerUrl ldaps://ldap.jumpcloud.com:636 -LdapBaseDn "ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com -LdapUserGroup wayk-users"
----
